USE [master]
GO

/****** Object:  Database [TGProject]    Script Date: 2.06.2021 13:12:18 ******/
CREATE DATABASE [TGProject]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TGProject', FILENAME = N'C:\Users\ultio\TGProject.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TGProject_log', FILENAME = N'C:\Users\ultio\TGProject_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TGProject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TGProject] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TGProject] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TGProject] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TGProject] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TGProject] SET ARITHABORT OFF 
GO

ALTER DATABASE [TGProject] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TGProject] SET AUTO_SHRINK OFF s
GO

ALTER DATABASE [TGProject] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TGProject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TGProject] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TGProject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TGProject] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TGProject] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TGProject] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TGProject] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TGProject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TGProject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TGProject] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TGProject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TGProject] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TGProject] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TGProject] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TGProject] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TGProject] SET  MULTI_USER 
GO

ALTER DATABASE [TGProject] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TGProject] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TGProject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TGProject] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TGProject] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TGProject] SET QUERY_STORE = OFF
GO

USE [TGProject]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [TGProject] SET  READ_WRITE 
GO


